# 
GET http://localhost:3003/api/blogs

###
# 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Auto syttyi tuleen maan alla Tampereella – myös useita muita autoja tuhoutui rajussa parkkihalli­palossa",
    "author": "Kirsi Matson-Mäkelä, Antti Palomaa",
    "url": "https://yle.fi/a/74-20186043",
    "likes": "2"
}

###
# Create a user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "juuso",
    "password": "juusonsalasana",
    "name": "Juuso T"
}